name: Portal CI

on:
  push:
    branches: [hotfix/release-workflow]
jobs:
  build-win:
    runs-on: window-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .
        run: |
          . setup-virtualenv.sh
          . build-python.sh
          npm run publish

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          tag_name: ${{ steps.extract_branch.outputs.branch }}
          release_name: ${{ steps.extract_branch.outputs.branch }}
