name: Portal CI

on:
  push:
    branches: [hotfix/release-workflow]
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        # Install Node.js
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@datature"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Publish windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .
        run: |
          . ./setup-virtualenv.sh
          . ./build-python.sh
          npm run publish

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          tag_name: ${{ steps.extract_branch.outputs.branch }}
          release_name: ${{ steps.extract_branch.outputs.branch }}
